# 1. Cette ligne est INDISPENSABLE pour que le Podfile comprenne les commandes Flutter
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'

# 2. On charge les instructions Flutter
install! 'cocoapods', :deterministic_uuids => false

# Importation du script Flutter (C'est ce qui manquait !)
flutter_install_all_ios_pods = File.join(File.dirname(File.realpath(__FILE__)), '..', '.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 3. La commande qui faisait planter le build
  # Elle demande maintenant à Flutter d'installer tous les plugins
  # (Pas besoin de paramètre ici avec les versions récentes)
end

# 4. Ce bloc force la version 14.0 pour éviter l'erreur Google Maps
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end